### ISSUE TITLE
[artifactory-oss/jcr/cpp-ce] Artifactory dependency charts fails with jf-event issue when splitServicesToContainers is enabled

### ISSUE THREAD

**Issue by Nefelim4ag** [jfrog/charts#1639]
Must be disabled, because working only with enterprise image

```
artifactory:
  jfconnect: # Broken missing jfconnect in OSS image
    enabled: false
```

Not working because the missing jf-event in OSS image
```
artifactory:
  splitServicesToContainers: true
```

**Comment by chukka** [comment]
@Nefelim4ag Yes, This is already fixed  internally and will be released in  upcoming next minor release  of artifactory

**Comment by Nefelim4ag** [comment]
107.41.4 - same, missing jf-event

**Comment by chukka** [comment]
@Nefelim4ag  can you please share complete logs and reproducible steps ?

**Comment by Nefelim4ag** [comment]
artifactory-oss: 107.41.4

```
artifactory:
  splitServicesToContainers: true # Broken missing jf-events in OSS image
  artifactory:
    persistence:
      size: 100Gi
      storageClassName: "efs"
    resources:
      requests:
        memory: "2Gi"
        cpu: "200m"
    javaOpts:
      corePoolSize: 8
      jmx:
        authenticate: false
        enabled: false
        port: 9010
        ssl: false
      xms: "512m"
      xmx: "2g"
  ingress:
    enabled: true
    hosts:
      - artifactory-dev.example.net
    annotations:
      kubernetes.io/ingress.class: contour
      cert-manager.io/cluster-issuer: zerossl
    tls:
      - secretName: artifactory-tls
        hosts:
          - artifactory-dev.example.net

  jfconnect: # Broken missing jfconnect in OSS image
    enabled: false

  nginx:
    enabled: false

  postgresql:
    enabled: true
    postgresqlPassword: password
    global:
      storageClass: "ebs"
    persistence:
      enabled: true
      size: 16Gi
    resources:
     requests:
       memory: "256Mi"
       cpu: "100m"
```

**Comment by Nefelim4ag** [comment]
@chukka image 
`releases-docker.jfrog.io/jfrog/artifactory-oss:7.41.4`

So, no jf-event

```
bash-4.4$ ls -al /opt/jfrog/artifactory/app/
total 4
drwxrwxrwx 1 artifactory artifactory 202 Jul  6 19:29 .
drwxr-xr-x 1 artifactory artifactory  28 Jul  6 19:30 ..
drwxrwxrwx 4 artifactory artifactory  34 Jul  6 19:29 artifactory
-rwxrwxrwx 1 artifactory artifactory 174 Jul  6 19:17 artifactory.product.version.properties
drwxrwxrwx 3 artifactory artifactory 307 Jul  6 19:30 bin
drwxrwxrwx 2 artifactory artifactory 270 Jul  6 19:28 doc
drwxrwxrwx 3 artifactory artifactory  17 Jul  6 19:28 frontend
drwxrwxrwx 3 artifactory artifactory  17 Jul  6 19:28 integration
drwxrwxrwx 3 artifactory artifactory  17 Jul  6 19:28 metadata
drwxrwxrwx 6 artifactory artifactory  95 Jul  6 19:28 misc
drwxrwxrwx 3 artifactory artifactory  17 Jul  6 19:28 observability
drwxrwxrwx 3 artifactory artifactory  17 Jul  6 19:28 router
drwxrwxrwx 2 artifactory artifactory   6 Jul  6 19:29 run
drwxr-xr-x 8 artifactory artifactory  88 Jul  6 19:29 third-party
```

```
bash-4.4$ find /opt/ -name jf-event
```

**Comment by chukka** [comment]
Yes, Thanks for reporting ! we already added support to disable jf-event via values.yaml internally and  will be fixed in upcoming release

**Comment by Nefelim4ag** [comment]
```
2022-07-21T12:08:22.188Z [jfrou] [WARN ] [24052b61cd9bd0b9] [local_topology.go:274         ] [main                ] - Readiness test failed with the following error: "required node services are missing or unhealthy"
2022-07-21T12:08:26.006Z [jfrou] [WARN ] [03455cef6a7bdcd2] [local_topology_helper.go:65   ] [main                ] - Missing required services: [jfevt]
2022-07-21T12:08:27.192Z [jfrou] [WARN ] [7f2781dc5d2b024b] [local_topology_helper.go:65   ] [main                ] - Missing required services: [jfevt]
2022-07-21T12:08:27.192Z [jfrou] [WARN ] [7f2781dc5d2b024b] [local_topology.go:274         ] [main                ] - Readiness test failed with the following error: "required node services are missing or unhealthy"
2022-07-21T12:08:30.998Z [jfrou] [WARN ] [4f039419bf21907e] [local_topology_helper.go:65   ] [main                ] - Missing required services: [jfevt]
```

So, I just drop jf-event container from the pod, and to fix this error drop `jfevt` from jf-router list.

You already released 2 versions, and already said the same (we have fixed and we will release it) about a month ago: https://github.com/jfrog/charts/issues/1639#issuecomment-1146950673

So, I will return on next release :)

**Comment by chukka** [comment]
@Nefelim4ag  Sorry for the confusion ! It was partially fixed previously and we missed it . I will reopen until this is properly fixed

**Comment by chukka** [comment]
Update : Fix for this issue will be available in 7.42.x and above versions

**Comment by chukka** [comment]
@Nefelim4ag  can you try latest  oss chart `107.41.7` and share feedback

**Comment by Nefelim4ag** [comment]
Works, thanks!

**Comment by peterkimeli** [comment]
Works for me, thank you!
